# Generated by Django 4.2.30 on 2026-08-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
