# Generated by Django 4.2.30 on 2026-08-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_github_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='otp_code_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
