"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Single .env file for both environments; ENVIRONMENT picks which DATABASE_URL_* is
# active. Set ENVIRONMENT=production before running manage.py/gunicorn in prod.
load_dotenv(BASE_DIR / '.env')

# Normalized and validated against a known set on purpose: a typo like
# ENVIRONMENT=Production or ENVIRONMENT=prod must never silently fall back to
# development (DEBUG=True, no HSTS, no secure cookies) in a real deployment.
_VALID_ENVIRONMENTS = {'development', 'production'}
ENVIRONMENT = os.environ.get('ENVIRONMENT', 'development').strip().lower()
if ENVIRONMENT not in _VALID_ENVIRONMENTS:
    raise ImproperlyConfigured(
        f"ENVIRONMENT={ENVIRONMENT!r} is invalid; must be one of {sorted(_VALID_ENVIRONMENTS)}."
    )


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# No hardcoded fallback on purpose: a missing SECRET_KEY should fail loudly,
# not silently fall back to a key that might be sitting in git history somewhere.
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = ENVIRONMENT == 'development'

ALLOWED_HOSTS = [h for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h]

if ENVIRONMENT == 'production':
    # https://docs.djangoproject.com/en/4.2/topics/security/
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

_default_cors_origins = 'http://localhost:5173,http://127.0.0.1:5173' if ENVIRONMENT != 'production' else ''
CORS_ALLOWED_ORIGINS = [
    o for o in os.environ.get('CORS_ALLOWED_ORIGINS', _default_cors_origins).split(',') if o
]

REST_FRAMEWORK = {
    # Secure by default: endpoints must opt in to AllowAny explicitly (see core/views.py).
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# ENVIRONMENT=development (default) -> DATABASE_URL_DEV (local Postgres)
# ENVIRONMENT=production            -> DATABASE_URL_PROD (Supabase)

_database_url = os.environ['DATABASE_URL_PROD'] if ENVIRONMENT == 'production' else os.environ['DATABASE_URL_DEV']

DATABASES = {
    'default': dj_database_url.parse(_database_url, conn_max_age=600)
}

# Supabase's pgbouncer (transaction-mode pooler on port 6543) doesn't support
# server-side cursors; dj_database_url just drops the ?pgbouncer=true flag into
# OPTIONS, where psycopg2 would choke on it, so translate it into the real setting.
if DATABASES['default'].get('OPTIONS', {}).pop('pgbouncer', False):
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
