"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Single .env file for both environments; ENVIRONMENT picks which DATABASE_URL_* is
# active. Set ENVIRONMENT=production before running manage.py/gunicorn in prod.
load_dotenv(BASE_DIR / '.env')

# Normalized and validated against a known set on purpose: a typo like
# ENVIRONMENT=Production or ENVIRONMENT=prod must never silently fall back to
# development (DEBUG=True, no HSTS, no secure cookies) in a real deployment.
_VALID_ENVIRONMENTS = {'development', 'production'}
ENVIRONMENT = os.environ.get('ENVIRONMENT', 'development').strip().lower()
if ENVIRONMENT not in _VALID_ENVIRONMENTS:
    raise ImproperlyConfigured(
        f"ENVIRONMENT={ENVIRONMENT!r} is invalid; must be one of {sorted(_VALID_ENVIRONMENTS)}."
    )


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# No hardcoded fallback on purpose: a missing SECRET_KEY should fail loudly,
# not silently fall back to a key that might be sitting in git history somewhere.
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = ENVIRONMENT == 'development'

ALLOWED_HOSTS = [h for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h]

# Used below (REST_FRAMEWORK throttle rates) and further down (LOGGING levels)
# to quiet things down / relax limits specifically while `manage.py test` runs.
_RUNNING_TESTS = 'test' in sys.argv

if ENVIRONMENT == 'production':
    # https://docs.djangoproject.com/en/4.2/topics/security/
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

# JWT access/refresh tokens live in httpOnly cookies (see accounts/cookies.py,
# accounts/authentication.py) rather than being readable by frontend JS, so an
# XSS bug can't just read them out of localStorage. That means the browser now
# attaches them automatically on every request, which is exactly what SameSite
# and the CSRF double-submit check (CookieJWTAuthentication) exist to contain.
#
# SameSite=None requires Secure, and Secure cookies are never sent over plain
# http:// - so dev (http://localhost) uses Lax (sufficient there: frontend and
# backend differ only by port, which is the same "site"), and production uses
# None+Secure so it still works if frontend/backend end up on genuinely
# different domains, not just different subdomains of one.
#
# Cookie-based CSRF *requires* frontend and backend to share a registrable
# domain (e.g. app.example.com / api.example.com) - the frontend JS must be
# able to read the (non-httpOnly) csrftoken cookie via document.cookie to echo
# it back as a header, and cookies aren't readable across unrelated domains.
AUTH_COOKIE_SECURE = ENVIRONMENT == 'production'
AUTH_COOKIE_SAMESITE = 'None' if ENVIRONMENT == 'production' else 'Lax'
CSRF_COOKIE_SAMESITE = AUTH_COOKIE_SAMESITE
# CSRF_TRUSTED_ORIGINS is set below, once CORS_ALLOWED_ORIGINS exists.

# Only needed once frontend/backend are deployed as subdomains of one domain
# (e.g. api.example.com / app.example.com, as opposed to dev's same-site
# different-port setup) - makes the csrftoken cookie visible to frontend JS
# across the subdomain boundary (see the paragraph above: without this it's
# host-only, so document.cookie on app.example.com never sees a cookie set by
# api.example.com, and every mutating request 403s "CSRF token missing").
# Leading dot is the traditional "this domain and all subdomains" form; left
# unset (the default), cookies stay host-only, correct for dev.
CSRF_COOKIE_DOMAIN = os.environ.get('COOKIE_DOMAIN') or None


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'core',
    'accounts',
    'analyses',
    'ai',
    'adminapi',
    'chat',
    'github_integration',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves collected static files (admin CSS/JS) directly from gunicorn -
    # django.contrib.staticfiles only auto-serves under `runserver`/DEBUG, and
    # this app has no separate static-file server/CDN in front of it. Must sit
    # directly after SecurityMiddleware per whitenoise's own setup docs.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

_default_cors_origins = 'http://localhost:5173,http://127.0.0.1:5173' if ENVIRONMENT != 'production' else ''
CORS_ALLOWED_ORIGINS = [
    o for o in os.environ.get('CORS_ALLOWED_ORIGINS', _default_cors_origins).split(',') if o
]
# Cookies (JWT + CSRF) must be allowed to flow with cross-origin requests -
# the frontend and backend are separate origins even in dev (5173 vs 8000).
CORS_ALLOW_CREDENTIALS = True
# Django's CSRF check validates the request's Origin/Referer against this list
# for any cookie-authenticated unsafe request (see accounts/authentication.py).
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS

# Baseline throttle rates, keyed by 'scope' (see core/throttling.py for the
# named ScopedRateThrottle subclasses that opt individual views into these).
# 'anon' and 'user' are applied to every view automatically (DEFAULT_THROTTLE_CLASSES
# below); the rest only apply to views that explicitly set throttle_classes.
# During `manage.py test` these are widened to effectively unlimited - the
# Django test client reuses the same REMOTE_ADDR for every request, so real
# rates would make unrelated tests bleed into each other's throttle counters
# (LocMemCache persists for the whole test-run process). Tests that need to
# exercise real throttling do so with their own override_settings + cache.clear().
_THROTTLE_RATES = {
    'anon': '60/min',
    'user': '300/min',
    'login': '10/min',
    'register': '5/hour',
    'password_reset': '20/hour',
    # otp_verify is an IP-level backstop - the real brute-force defense is
    # the per-account expiry + attempt-lockout in accounts/otp.py.
    'otp_verify': '20/hour',
    'otp_resend': '5/hour',
    'ai': '30/min',
    'analysis_create': '30/min',
}
if _RUNNING_TESTS:
    _THROTTLE_RATES = {scope: '1000000/day' for scope in _THROTTLE_RATES}

REST_FRAMEWORK = {
    # Secure by default: endpoints must opt in to AllowAny explicitly (see core/views.py).
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.authentication.CookieJWTAuthentication',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': _THROTTLE_RATES,
    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
}

# Email - sent via Brevo's transactional email API (accounts/brevo_client.py),
# not Django's own mail backends/SMTP. Optional at startup, same pattern as
# GROQ_API_KEY etc: BrevoClient raises ImproperlyConfigured lazily on first
# real send, not at boot, so the app still starts without it configured.
BREVO_API_KEY = os.environ.get('BREVO_API_KEY', '')
# Must be a verified sender/domain in the Brevo account - see
# https://app.brevo.com/senders/list.
BREVO_SENDER_EMAIL = os.environ.get('BREVO_SENDER_EMAIL', '')
BREVO_SENDER_NAME = os.environ.get('BREVO_SENDER_NAME', 'Code Analyzer')

# Base URL of the frontend app, used to build links inside verification/reset emails.
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

# AI provider chain (ai/client.py) - powers the AI suggestions/explanation/
# refactor/chat endpoints. Groq is tried first; on any failure (rate limit,
# outage, missing key) it falls back to Gemini, then to OpenRouter. All three
# are optional - a provider with no key configured is just skipped.
GROQ_API_KEY = os.environ.get('GROQ_API_KEY', '')
GROQ_MODEL = os.environ.get('GROQ_MODEL', 'llama-3.3-70b-versatile')

GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '')
# "gemini-flash-latest" is a Google-maintained alias, not a snapshot - pinning
# a dated model (e.g. "gemini-2.5-flash") risks 404s as older snapshots get
# retired from new-user/free-tier access.
GEMINI_MODEL = os.environ.get('GEMINI_MODEL', 'gemini-flash-latest')

OPENROUTER_API_KEY = os.environ.get('OPENROUTER_API_KEY', '')
OPENROUTER_MODEL = os.environ.get('OPENROUTER_MODEL', 'openrouter/auto')

# Celery - runs the GitHub PR analysis pipeline off the request path (a webhook
# must be acknowledged in seconds or GitHub retries the delivery). Redis is
# used as both broker and result backend; no separate results database/table
# is needed since task outcomes are already persisted as WebhookEvent/
# PullRequestAnalysis rows, which are the real source of truth.
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_TIME_LIMIT = 300
# Runs tasks synchronously, in-process, when true - used by the test suite so
# "queue a Celery task" tests don't need a real worker/broker running.
CELERY_TASK_ALWAYS_EAGER = os.environ.get('CELERY_TASK_ALWAYS_EAGER', '').lower() == 'true'
CELERY_TASK_EAGER_PROPAGATES = True

# Google Sign-In: Google Identity Services on the frontend hands us a signed
# ID token, which accounts/google_auth.py verifies server-side against this
# client ID. Deliberately no GOOGLE_CLIENT_SECRET, unlike the GitHub OAuth App
# below - this is ID-token verification, not a redirect/code-exchange flow,
# and OAuth client IDs aren't secret (they ship inside the public frontend
# bundle by design). Optional at startup, same as GITHUB_CLIENT_ID below.
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '')

# GitHub OAuth App (https://github.com/settings/developers - "OAuth Apps", not
# a GitHub App) + webhook secret + the key used to encrypt stored access
# tokens at rest. All optional at startup - endpoints that need one of these
# return a clear 503 rather than the whole app failing to boot when GitHub
# integration hasn't been configured yet (same pattern as GROQ_API_KEY above).
GITHUB_CLIENT_ID = os.environ.get('GITHUB_CLIENT_ID', '')
GITHUB_CLIENT_SECRET = os.environ.get('GITHUB_CLIENT_SECRET', '')
# Where GitHub redirects back to after the user approves access - must exactly
# match one of the "Authorization callback URL" values on the OAuth App.
GITHUB_OAUTH_REDIRECT_URI = os.environ.get(
    'GITHUB_OAUTH_REDIRECT_URI', 'http://localhost:8000/api/github/callback/',
)
# Shared secret configured on each webhook GitHubClient creates, used to
# verify the X-Hub-Signature-256 header on every incoming webhook POST.
GITHUB_WEBHOOK_SECRET = os.environ.get('GITHUB_WEBHOOK_SECRET', '')
# Fernet key (Fernet.generate_key()) encrypting GitHubIntegration.access_token
# at rest - see github_integration/services/encryption.py.
GITHUB_TOKEN_ENCRYPTION_KEY = os.environ.get('GITHUB_TOKEN_ENCRYPTION_KEY', '')
# Publicly reachable base URL GitHub can deliver webhooks to (ngrok/deployed
# host in practice - GitHub cannot reach "localhost"). Used to build the
# webhook URL passed to GitHubClient.create_webhook().
GITHUB_WEBHOOK_BASE_URL = os.environ.get('GITHUB_WEBHOOK_BASE_URL', 'http://localhost:8000')
# Files larger than this are skipped entirely rather than analyzed - keeps a
# single huge changed file (e.g. an accidentally-committed data dump) from
# blowing up analysis time/cost.
GITHUB_MAX_FILE_SIZE_BYTES = int(os.environ.get('GITHUB_MAX_FILE_SIZE_BYTES', 500_000))
# Caps how many files a single repository-index build (see
# github_integration/services/repo_index_service.py) will fetch content for -
# indexing costs one GitHub API call per file, so an uncapped build on a huge
# repo could exhaust the rate limit. Repos with more indexable files than this
# get a partial graph (RepositoryIndex.truncated=True) rather than failing outright.
GITHUB_MAX_INDEXED_FILES = int(os.environ.get('GITHUB_MAX_INDEXED_FILES', 300))

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# ENVIRONMENT=development (default) -> DATABASE_URL_DEV (local Postgres)
# ENVIRONMENT=production            -> DATABASE_URL_PROD (Supabase)

_database_url = os.environ['DATABASE_URL_PROD'] if ENVIRONMENT == 'production' else os.environ['DATABASE_URL_DEV']

DATABASES = {
    'default': dj_database_url.parse(_database_url, conn_max_age=600)
}

# Supabase's pgbouncer (transaction-mode pooler on port 6543) doesn't support
# server-side cursors; dj_database_url just drops the ?pgbouncer=true flag into
# OPTIONS, where psycopg2 would choke on it, so translate it into the real setting.
if DATABASES['default'].get('OPTIONS', {}).pop('pgbouncer', False):
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
# Where `collectstatic` gathers files for WhiteNoise (see MIDDLEWARE above) to
# serve - required for collectstatic to run at all; without it the command
# fails with "you're using the staticfiles app without STATIC_ROOT set".
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Adds a content hash to filenames and lets WhiteNoise set far-future cache
# headers safely (a new deploy produces new hashed filenames, so browsers
# never serve a stale cached asset under an old one's URL).
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (user uploads, e.g. avatars)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Logging
# StructuredFormatter appends any `extra={...}` passed to a log call as a
# trailing JSON blob - without it those fields are silently dropped, which
# would defeat the point of the structured logger.info(..., extra={...})
# calls throughout github_integration (OAuth, webhooks, Celery jobs, GitHub
# API requests, comment posting, failures).
# Quieter during `manage.py test`: the suite deliberately exercises every
# logged failure path (invalid signatures, retries exhausted, etc.), and at
# INFO those all print - WARNING keeps real problems visible without the noise.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'structured': {
            '()': 'core.logging_formatters.StructuredFormatter',
            'format': '%(asctime)s %(levelname)s %(name)s: %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'structured',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING' if _RUNNING_TESTS else 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'github_integration': {
            'handlers': ['console'],
            'level': 'WARNING' if _RUNNING_TESTS else 'INFO',
            'propagate': False,
        },
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
