# Generated by Django 4.2.30 on 2026-07-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='issues',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='analysis',
            name='source_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
