# Generated by Django 4.2.30 on 2026-07-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0002_analysis_issues_analysis_source_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='ai_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='ai_refactored_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='ai_suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
