# Generated by Django 4.2.30 on 2026-07-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0003_analysis_ai_explanation_analysis_ai_refactored_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='ai_refactor_explanation',
            field=models.TextField(blank=True),
        ),
    ]
