# Generated by Django 4.2.30 on 2026-07-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0004_analysis_ai_refactor_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='security_report',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
