# Generated by Django 4.2.30 on 2026-08-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0005_analysis_security_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='repo_context',
            field=models.TextField(blank=True),
        ),
    ]
