# Generated by Django 4.2.30 on 2026-07-26 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_user_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(max_length=255)),
                ('access_token', models.BinaryField()),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('token_invalid', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_integration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GitHubRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_id', models.BigIntegerField()),
                ('full_name', models.CharField(max_length=255)),
                ('default_branch', models.CharField(default='main', max_length=255)),
                ('webhook_id', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='github_integration.githubintegration')),
            ],
            options={
                'verbose_name_plural': 'GitHub repositories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('delivery_id', models.CharField(max_length=100, unique=True)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PullRequestAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pull_request_number', models.PositiveIntegerField()),
                ('commit_sha', models.CharField(max_length=40)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('review_posted', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_request_analyses', to='github_integration.githubrepository')),
            ],
            options={
                'verbose_name_plural': 'pull request analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1000)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pull_request_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_analyses', to='github_integration.pullrequestanalysis')),
            ],
            options={
                'verbose_name_plural': 'file analyses',
                'ordering': ['file_path'],
            },
        ),
        migrations.AddConstraint(
            model_name='pullrequestanalysis',
            constraint=models.UniqueConstraint(fields=('repository', 'pull_request_number', 'commit_sha'), name='unique_pr_commit_analysis'),
        ),
        migrations.AddConstraint(
            model_name='githubrepository',
            constraint=models.UniqueConstraint(fields=('integration', 'repository_id'), name='unique_repo_per_integration'),
        ),
    ]
