# Generated by Django 4.2.30 on 2026-07-27 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('github_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryFileCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1000)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_checks', to='github_integration.githubrepository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_file_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
