# Generated by Django 4.2.30 on 2026-07-27 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0005_analysis_security_report'),
        ('github_integration', '0002_repositoryfilecheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryfilecheck',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='analyses.analysis'),
        ),
    ]
