# Generated by Django 4.2.30 on 2026-08-03 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github_integration', '0003_repositoryfilecheck_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('files_total', models.PositiveIntegerField(default=0)),
                ('files_indexed', models.PositiveIntegerField(default=0)),
                ('truncated', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='index', to='github_integration.githubrepository')),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryFileNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1000)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('summary', models.TextField(blank=True)),
                ('imports', models.JSONField(blank=True, default=list)),
                ('imported_by', models.JSONField(blank=True, default=list)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='github_integration.repositoryindex')),
            ],
            options={
                'ordering': ['path'],
            },
        ),
        migrations.AddConstraint(
            model_name='repositoryfilenode',
            constraint=models.UniqueConstraint(fields=('index', 'path'), name='unique_file_node_per_index'),
        ),
    ]
