# Generated by Django 4.2.30 on 2026-08-05 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0006_analysis_repo_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('github_integration', '0004_repositoryindex_repositoryfilenode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryContextCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1000)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('score', models.FloatField(blank=True, null=True)),
                ('related', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='analyses.analysis')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_checks', to='github_integration.githubrepository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_context_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
