# Generated by Django 4.2.30 on 2026-08-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_integration', '0005_repositorycontextcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorycontextcheck',
            name='context_truncated_reason',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
