# Generated by Django 4.2.30 on 2026-08-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_integration', '0006_repositorycontextcheck_context_truncated_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorycontextcheck',
            name='degraded_stages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
