# Generated by Django 4.2.30 on 2026-08-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_integration', '0007_repositorycontextcheck_degraded_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='hook_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
